accounts:
  - name: alice
    coins: ["20000token", "2000000metab", "200000000stake"]
  - name: bob
    coins: ["10000token", "10000000metab", "100000000stake"]
  - name: laotie
    coins: ["1token", "2metab", "2000000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
